[package]

name = "iron_llvm"
version = "0.0.1"
authors = ["Jauhien Piatlicki <jauhien@gentoo.org>"]
build = "build.rs"

[dependencies]
libc = "< 0.2"
llvm-sys = "*"

[build-dependencies]
cmake = "*"
